server:
    port: 8761
    sererlet:
        context-path: /eureka
eureka:
    instance:
        hostname: localhost
client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
